# Generate pdf using pdflatex (-pdf)
$pdf_mode = 1;

# Use bibtex if a .bib file exists
$bibtex_use = 1;

# Define command to compile with pdfsync support and nonstopmode
$pdflatex = 'pdflatex -synctex=1 --interaction=nonstopmode -file-line-error -shell-escape';

# Use default pdf viewer - use latexmk -pv    (or -pvc)
$pdf_previewer = 'evince';

# remove additional items for latexmk -c
$clean_ext = 'pdfsync synctex.gz dvi pyg';

# output dir
$out_dir = 'build'

